services:
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "27018:27017"
    networks:
      - testnet

  test:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - ORIGIN=${ORIGIN}
      - PUBLIC_REFRESH_TOKEN_KEY=${PUBLIC_REFRESH_TOKEN_KEY}
      - PRIVATE_REFRESH_TOKEN_KEY=${PRIVATE_REFRESH_TOKEN_KEY}
      - PUBLIC_ACCESS_TOKEN_KEY=${PUBLIC_ACCESS_TOKEN_KEY}
      - PRIVATE_ACCESS_TOKEN_KEY=${PRIVATE_ACCESS_TOKEN_KEY}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    depends_on:
      - db
    command: ["npm", "run", "test:run"]
    networks:
      - testnet

networks:
  testnet:
    driver: bridge
