version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "${PORT}:${PORT}"
    environment:
      - MONGO_URI=${DEV_MONGO_URI}
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DEV_MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DEV_MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=test
    ports:
      - "27017:27017"
