version: "3.9"

services:
  db:
    image: mongo:latest
    env_file:
      - .env.test
    ports:
      - "27018:27017"

  test:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.test
    depends_on:
      - db
    command: ["npm", "run", "test:run"]
