export default {
  type: "object",
  required: [
    "PORT",
    "MONGO_URI",
    "ORIGIN",
    "COOKIE_SECRET",
    "PUBLIC_REFRESH_TOKEN_KEY",
    "PRIVATE_REFRESH_TOKEN_KEY",
    "PUBLIC_ACCESS_TOKEN_KEY",
    "PRIVATE_ACCESS_TOKEN_KEY",
    // "GOOGLE_CLIENT_ID",
    // "GOOGLE_CLIENT_SECRET",
    // "GOOGLE_CALLBACK_URL",
  ],
  properties: {
    PORT: { type: "string" },
    MONGO_URI: { type: "string" },
    ORIGIN: { type: "string" },
    COOKIE_SECRET: { type: "string" },
    GOOGLE_CLIENT_ID: { type: "string" },
    GOOGLE_CLIENT_SECRET: { type: "string" },
    GOOGLE_CALLBACK_URL: { type: "string" },
    PUBLIC_REFRESH_TOKEN_KEY: { type: "string" },
    PRIVATE_REFRESH_TOKEN_KEY: { type: "string" },
    PUBLIC_ACCESS_TOKEN_KEY: { type: "string" },
    PRIVATE_ACCESS_TOKEN_KEY: { type: "string" },
  },
};
