export default {
  type: "object",
  required: [
    "PORT",
    "COOKIE_SECRET",
    "PUBLIC_REFRESH_TOKEN_KEY",
    "PRIVATE_REFRESH_TOKEN_KEY",
    "PUBLIC_ACCESS_TOKEN_KEY",
    "PRIVATE_ACCESS_TOKEN_KEY",
    "MONGO_HOST",
    "MONGO_INITDB_ROOT_USERNAME",
    "MONGO_INITDB_ROOT_PASSWORD",
    "MONGO_INITDB_DATABASE",
    "MONGO_PORT",
  ],
  properties: {
    PORT: { type: "string" },
    COOKIE_SECRET: { type: "string" },
    GOOGLE_CLIENT_ID: { type: "string" },
    GOOGLE_CLIENT_SECRET: { type: "string" },
    GOOGLE_CALLBACK_URL: { type: "string" },
    PUBLIC_REFRESH_TOKEN_KEY: { type: "string" },
    PRIVATE_REFRESH_TOKEN_KEY: { type: "string" },
    PUBLIC_ACCESS_TOKEN_KEY: { type: "string" },
    PRIVATE_ACCESS_TOKEN_KEY: { type: "string" },
    MONGO_HOST: { type: "string" },
    MONGO_INITDB_ROOT_USERNAME: { type: "string" },
    MONGO_INITDB_ROOT_PASSWORD: { type: "string" },
    MONGO_INITDB_DATABASE: { type: "string" },
    MONGO_PORT: { type: "string" },
  },
};
